# Generated by Django 4.0.6 on 2022-07-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('fullname', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('songaypheptheonam', models.IntegerField()),
                ('songayphepconlai', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
